### PR TITLE
GHC 8.8 compatibility

### LINKED ISSUE #33: Incompatible with ghc8.8 due to MonadFail
```
% stack --resolver lts-15.11 build ztar

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for ztar-1.0.1:
    path-0.7.0 from stack configuration does not match >=0.5 && <0.7  (latest matching version is 0.6.1)
    zip-1.3.2 from stack configuration does not match >=1.0 && <1.3  (latest matching version is 1.2.0)
needed since ztar is a build target.

Some different approaches to resolving this:

  * Set 'allow-newer: true'
    in /Users/liam/.stack/config.yaml to ignore all version constraints and build anyway.

  * Recommended action: try adding the following to your extra-deps
    in /Users/liam/.stack/global-project/stack.yaml:

- path-0.6.1@sha256:7a9a56f767a8e47b361af855fea0b4a8d18e7b029734957a65dcd5c0c1abef16,2423
- zip-1.2.0@sha256:b7265f229c47a47c3ddf7e3334c3d0811c35e46a2a4bbae7b532541802445325,4458

Plan construction failed.
```

Added these to my global stack.yaml, then
```
% stack --resolver lts-15.11 build ztar
...
ztar                 > configure
ztar                 > Configuring ztar-1.0.1...
ztar                 > build
ztar                 > Preprocessing library for ztar-1.0.1..
ztar                 > Building library for ztar-1.0.1..
ztar                 > 
ztar                 > on the commandline: warning:
ztar                 >     -Wnoncanonical-monadfail-instances is deprecated: fail is no longer a method of Monad
ztar                 > [1 of 6] Compiling Codec.Archive.Tar
ztar                 > [2 of 6] Compiling Codec.Archive.ZTar.GZip
ztar                 > [3 of 6] Compiling Codec.Archive.ZTar.Tar
ztar                 > [4 of 6] Compiling Codec.Archive.ZTar.Zip
ztar                 > 
ztar                 > /private/var/folders/b4/vndwlkd168l7lnn9zcq_3y080000gn/T/stack-f426e50fcdcf04a2/ztar-1.0.1/src/Codec/Archive/ZTar/Zip.hs:68:24: error:
ztar                 >     • No instance for (MonadFail Zip.ZipArchive)
ztar                 >         arising from a use of ‘fail’
ztar                 >     • In the expression: fail $ "Path does not exist: " ++ path
ztar                 >       In a stmt of a 'do' block:
ztar                 >         if | isFile -> insertFile path
ztar                 >            | isDir -> insertDir path
ztar                 >            | otherwise -> fail $ "Path does not exist: " ++ path
ztar                 >       In the expression:
ztar                 >         do isFile <- liftIO $ doesFileExist path
ztar                 >            isDir <- liftIO $ doesDirectoryExist path
ztar                 >            if | isFile -> insertFile path
ztar                 >               | isDir -> insertDir path
ztar                 >               | otherwise -> fail $ "Path does not exist: " ++ path
ztar                 >    |
ztar                 > 68 |         | otherwise -> fail $ "Path does not exist: " ++ path
ztar                 >    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ztar                 > 
Completed 43 action(s).
```

So we cannot fail within the ZipArchive monad. @brandonchinn178 what would you like done to fix this, there are many possibilities?

### PR DESCRIPTION
**Pull request by liam-ly**
* `fail` was being applied to `ZipArchive` which no longer had a compatible instance.
* failure was due to IO issues, so a simple `liftIO` would have been sufficient.
* However, I separated the IO actions from the ZipArchive action instead of mixing them together.
* Using an up-to-date package that provides arbitrary bytestring instances.

ghc8.8.3 works locally for me now.
```bash
stack --resolver lts-15.11 build
stack --resolver lts-15.11 test
stack --resolver lts-15.11 install hlint stylish-haskell
stack --resolver lts-15.11 exec hlint .
find . -iname \*.hs -exec stack --resolver lts-15.11 exec stylish-haskell -- --inplace '{}' \;
```

Resolves #33

### CODE REVIEW

File: src/Codec/Archive/ZTar/Zip.hs [hunk 1]
```diff
@@ -57,21 +58,25 @@ create :: FilePath -- ^ archive to create
        -> IO ()
 create archive base paths = do
   archive' <- makeAbsolute archive
-  withCurrentDirectory base $ Zip.createArchive archive' $ mapM_ insert paths
+  withCurrentDirectory base $ do
+    files <- concatMapM search paths
```
Comment (brandonchinn178) [inline src/Codec/Archive/ZTar/Zip.hs:62]: wow this is so much better haha

File: package.yaml [hunk 2]
```diff
@@ -36,10 +38,11 @@ library:
     base: '>= 4.7 && < 5'
     bytestring: '>= 0.10.8 && < 0.11'
     directory: '>= 1.3 && < 1.4'
+    extra:
```
Comment (brandonchinn178) [inline package.yaml:41]: i'd prefer not to drag in the huge `extra` library. would you be ok with implementing `concatMapM` manually?

Comment (liam-ly) [reply package.yaml]: done and re-ran tests locally

File: src/Codec/Archive/ZTar/Zip.hs [hunk 3]
```diff
@@ -57,21 +58,26 @@ create :: FilePath -- ^ archive to create
...
       if
-        | isFile -> insertFile path
-        | isDir -> insertDir path
+        | isFile -> pure [path]
+        | isDir -> searchDir path
         | otherwise -> fail $ "Path does not exist: " ++ path
+    searchDir :: FilePath -> IO [FilePath]
+    searchDir path =
+      let mkPath = if path == "." then id else (path </>)
+      in concatMapM (search . mkPath) =<< liftIO (listDirectory path)
```
Comment (liam-ly) [inline src/Codec/Archive/ZTar/Zip.hs:76]: Oops - this `liftIO` is unnecessary, so I'm going to remove it

File: src/Codec/Archive/ZTar/Zip.hs [hunk 4]
```diff
@@ -57,21 +58,26 @@ create :: FilePath -- ^ archive to create
...
+    searchDir path =
+      let mkPath = if path == "." then id else (path </>)
+      in concatMapM (search . mkPath) =<< listDirectory path
     insertFile path = do
       path' <- Zip.mkEntrySelector path
       Zip.loadEntry Zip.BZip2 path' path
-    insertDir path =
-      let mkPath = if path == "." then id else (path </>)
-      in mapM_ (insert . mkPath) =<< liftIO (listDirectory path)
+    concatMapM f = liftM concat . mapM f
```
Comment (brandonchinn178) [inline src/Codec/Archive/ZTar/Zip.hs:80]: why not just fmap?

Comment (liam-ly) [reply src/Codec/Archive/ZTar/Zip.hs:80]: This was in the GHC proposal for adding concatMapM to base. Tell me what you want written and I'll change it; I'm not going to make guesses about the aesthetics.

Comment (brandonchinn178) [reply src/Codec/Archive/ZTar/Zip.hs:80]: oh ok, that's fine. just curious

Comment (liam-ly) [reply src/Codec/Archive/ZTar/Zip.hs:80]: I guess the reason is that `liftM` is not necessarily identical to `fmap` for all implementations of a Monad.

Comment (brandonchinn178) [reply src/Codec/Archive/ZTar/Zip.hs:80]: makes sense. but isn't it a monad law that
```hs
m >>= return . f
```
is equivalent to
```hs
f <$> m
```
? i don't see why `liftM` shouldn't be considered equivalent to `fmap`

Comment (liam-ly) [reply src/Codec/Archive/ZTar/Zip.hs:80]: You can make a Monad that doesn't obey the law, so for a `base` package, this implementation would make sense. This is in a specific monad anyway, so it doesn't need to generalize or account for the possibilities that monads don't obey these laws. You're welcome to change it; I just picked the first implementation of concatMapM I came across. This really doesn't matter to me.

The proposal is _quite_ old, so maybe there is some historical reason they wrote it like this.
https://gitlab.haskell.org/ghc/ghc/issues/2042
